name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.NAME }} --password=${{ secrets.KEY }} 
        # 使用Dockerfile构建镜像
        docker build . --file Dockerfile --tag dqk520/jupyterlab
        # 推送镜像到镜像仓库
        docker push dqk520/jupyterlab
